version: '3.7'

services:
  nginx:
    build: src/nginx
    ports:
      - 1337:80
    depends_on: 
      - webshop
  webshop:
    build: src/backend/
    command: gunicorn webshop.wsgi:application --bind 0.0.0.0:8000
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: